fix #1006 ユーティリティ：バックアップダウンロードAPIを実装
baserproject/ucmitz pull request #1018
Opened 2022-09-22 08:32 UTC by HungDV2022

2022-09-22 08:35 UTC, HungDV2022 commented
@ryuring
こちらのユニットテストの実装方法を教えていただけませんか

2022-09-22 08:59 UTC, ryuring commented
@HungDV2022 
- ステータスの確認
- 失敗した時のメッセージの確認
になりますかね。

失敗が検知できない処理になってましたので、調整してみました。
https://github.com/baserproject/ucmitz/commit/81f68ea12b76ed368609b950a71332adc2f5163b

2022-09-26 07:58 UTC, ryuring requested changes

2022-09-26 07:58 UTC, ryuring commented on plugins/baser-core/src/Controller/Api/UtilitiesController.php
> +                $message = __d('baser', 'バックアップダウンロードが成功しました。');
@HungDV2022 この処理だと、処理結果としてはJSONになってしまい、ZIPファイルのダウンロードにはならないと思います。

$this->autoRender = false;
にしてメッセージはいらないので、return してください。

2022-09-26 07:58 UTC, ryuring commented on plugins/baser-core/tests/TestCase/Controller/Api/UtilitiesControllerTest.php
> +        $this->assertEquals('バックアップダウンロードが成功しました。', $result->message);
@HungDV2022 失敗の処理が書かれてません。
TMP . 'schema' の書き込み権限を無くす等の処理を行って失敗させることはできませんか？？

2022-09-26 09:54 UTC, HungDV2022 commented on plugins/baser-core/src/Controller/Api/UtilitiesController.php
> +                $message = __d('baser', 'バックアップダウンロードが成功しました。');
@ryuring 
こちらを修正しました
確認お願いします

2022-09-26 09:55 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/Controller/Api/UtilitiesControllerTest.php
> +        $this->assertEquals('バックアップダウンロードが成功しました。', $result->message);
@ryuring 
何回を試しましたが400ステータスを返さなかったです。
どうすればいいですか

2022-09-27 07:05 UTC, ryuring commented
@HungDV2022 こちら手動作業でマージしました。
失敗のテストを作るために、本体処理側に is_writeble() などで判定を入れたのですが、うまく判定されず、失敗のテストは一旦あきらめました。
https://github.com/baserproject/ucmitz/commit/368bdf6d18f942d7ae2641336a7f08081410a5fa

2022-09-27 07:05 UTC, closed without merging