とりあえず、ダッシュボード表示される部分までしました
baserproject/ucmitz pull request #105
Opened 2021-05-13 08:53 UTC by humuhimi

- siteConfigsテーブルの追加
- TemplateListリストの変更・ユニットテスト
- dashboardControllerのindex
- templatePathの追加・ユニットテスト
- 未実装部分のjsをTODOに変更
![image](https://user-images.githubusercontent.com/35215680/118102701-b046c500-b40b-11eb-90b4-8a3db6e8c1a6.png)

2021-05-14 02:41 UTC, ryuring requested changes
@humuhimi レビューしました。

レビューを受けて改修する際は、一つ一つのコメントに回答をお願いします。

2021-05-14 02:41 UTC, ryuring commented on plugins/baser-core/config/setting.php
> +        'templateExt' => '.php',
@humuhimi Cake4から、デフォルトの拡張子が .php になったみたいです。
これはもう不要ですね
https://book.cakephp.org/4/ja/views.html#view-templates

2021-05-14 02:41 UTC, ryuring commented on plugins/baser-core/src/Controller/Admin/DashboardController.php
> +        $this->set('panels', $panels);
インデント

2021-05-14 02:41 UTC, ryuring commented on plugins/baser-core/src/Controller/Admin/DashboardController.php
> +        $this->setTitle(__d('baser', 'ダッシュボード'));
インデント

2021-05-14 02:41 UTC, ryuring commented on plugins/baser-core/src/Controller/BcAppController.php
> +        // if (isConsole()) {
isConsole を BcUtilに移動してそちらに実装お願いします

2021-05-14 02:41 UTC, ryuring commented on plugins/baser-core/src/Controller/BcAppController.php
>  		$this->ext = Configure::read('BcApp.templateExt');
これは不要ですね

2021-05-14 02:41 UTC, ryuring commented on plugins/baser-core/src/Model/Table/SiteConfigsTable.php
> +class SiteConfigsTable extends Table
AppTableを継承させてください

2021-05-14 02:41 UTC, ryuring commented on plugins/baser-core/src/Model/Table/SiteConfigsTable.php
> +	 * @since basercms4
@humuhimi これはどういう意味？

2021-05-14 02:41 UTC, ryuring commented on plugins/baser-core/src/Model/Table/SiteConfigsTable.php
> +     * @param array $config
全体的なインデントの調整をお願いします

2021-05-14 02:41 UTC, ryuring commented on plugins/baser-core/src/Model/Table/SiteConfigsTable.php
> +class SiteConfigsTable extends Table
また、SiteConfig は桃井さんが改修中だったような。
一度確認したほうがいいかも 
@momofff 大丈夫ですか？？

2021-05-14 02:41 UTC, ryuring commented on plugins/baser-core/src/Utility/BcUtil.php
> +            $templatesPathes = App::classPath('View');
@humuhimi 今回、プラグインじゃない場合ってどういう場合でしょう？

2021-05-14 02:41 UTC, ryuring commented on plugins/baser-core/src/Utility/BcUtil.php
> +        return str_replace('src/', '', App::classPath('templates', $plugin));
templates ってクラスじゃないのに、classPath で取得するのが気持ち悪いですね。仕様変更とかされそう。
プラグインのパスに、templates を付ける方向にしましょうか。

2021-05-14 02:41 UTC, ryuring commented on plugins/bc-admin-third/templates/Admin/Dashboard/index.php
> +
このファイルの元となっていたファイルは削除しましたか？

2021-05-14 06:21 UTC, humuhimi reviewed
レビュー後プッシュしました。再確認お手数ですが、よろしくおねがいします。

2021-05-14 06:21 UTC, humuhimi commented on plugins/baser-core/src/Utility/BcUtil.php
> +        return str_replace('src/', '', App::classPath('templates', $plugin));
Plugin::pathで代用しました。

2021-05-18 03:50 UTC, ryuring commented on plugins/baser-core/src/Model/Table/SiteConfigsTable.php
> +	 * @since basercms4
@humuhimi noCheckがその意味だから外そうか

2021-05-18 03:55 UTC, ryuring commented on plugins/baser-core/src/Utility/BcUtil.php
> +        return [Plugin::path($plugin) . 'templates/'];
@humuhimi これって配列にする意味ってあります？

2021-05-18 03:55 UTC, ryuring commented
@humuhimiもっかいレビューいれました

2021-05-18 10:04 UTC, merged