fix #1105 ブログカテゴリーリスト取得 API実装
baserproject/ucmitz pull request #1122
Opened 2022-10-04 08:56 UTC by HungDV2022

2022-10-04 11:00 UTC, ryuring requested changes

2022-10-04 11:00 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/Controller/Api/BlogCategoriesControllerTest.php
> +        $key = 3;
@HungDV2022 これは変数にする必要なさそうですね

2022-10-04 11:53 UTC, HungDV2022 commented on plugins/bc-blog/tests/TestCase/Controller/Api/BlogCategoriesControllerTest.php
> +        $key = 3;
@ryuring 
こちらを修正しました。
確認お願いします

2022-10-10 01:26 UTC, ryuring commented on plugins/bc-blog/src/Service/BlogCategoriesService.php
> +     * @noTodo
@HungDV2022 unitTest アノテーションが抜けています。

2022-10-10 01:28 UTC, ryuring commented
@HungDV2022 test_list()、test_getList() にて似たようなテストをしているのですが、それぞれテストの目的を考え、似たようなコードを作らないようにして欲しいです。

- test_list()：ステータス、戻り値が存在することの確認が目的（戻り値の中身はそれほど重要じゃない）
- test_getList()：戻り値の中身の確認が目的

2022-10-11 03:39 UTC, HungDV2022 commented on plugins/bc-blog/src/Service/BlogCategoriesService.php
> +     * @noTodo
@ryuring 
こちらを修正しました

確認お願いします

2022-10-11 04:14 UTC, merged