fix #1189 BcCkeditorHelper::setDraft() のユニットテスト実装
baserproject/ucmitz pull request #1274
Opened 2022-10-21 10:21 UTC by zebeel

2022-10-23 02:35 UTC, ryuring requested changes

2022-10-23 02:35 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcCkeditorHelperTest.php
> +        $this->BcCkeditor->BcAdminForm->create();
@zebeel 準備とそれぞれのテストの間に空行を入れてもらえると見やすくなるし助かります。
まずここ

2022-10-23 02:35 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcCkeditorHelperTest.php
> +        $this->assertCount(5, $result['editorToolbar'][0]);
次にここ

2022-10-23 02:35 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcCkeditorHelperTest.php
> +        $this->assertEquals('Test', $result['draftAreaId']);
そしてここ

内容はOKですので改行入れてくれたらマージします。

2022-10-24 07:43 UTC, zebeel commented on plugins/baser-core/tests/TestCase/View/Helper/BcCkeditorHelperTest.php
> +        $this->BcCkeditor->BcAdminForm->create();
対応済です。

2022-10-24 07:43 UTC, zebeel commented on plugins/baser-core/tests/TestCase/View/Helper/BcCkeditorHelperTest.php
> +        $this->assertCount(5, $result['editorToolbar'][0]);
対応済です。

2022-10-24 07:43 UTC, zebeel commented on plugins/baser-core/tests/TestCase/View/Helper/BcCkeditorHelperTest.php
> +        $this->assertEquals('Test', $result['draftAreaId']);
対応済です。ご確認お願い致します。

2022-10-25 06:21 UTC, merged