PluginsServiceのgetIndexのみ追加
baserproject/ucmitz pull request #141
Opened 2021-06-01 09:40 UTC by humuhimi

2021-06-01 10:19 UTC, ryuring requested changes
@humuhimi レビューしました調整お願いしますー

2021-06-01 10:19 UTC, ryuring commented on plugins/baser-core/src/Controller/Admin/PluginsController.php
> +        $this->set('sortmode', $this->request->getQuery('sortmode'));
sortmodeは、ビューで直接参照するようにしましょうか　@humuhimi

2021-06-01 10:19 UTC, ryuring commented on plugins/baser-core/src/Service/PluginsService.php
> +        $plugins = $sortMode ? $registered : array_merge($registered, $unregistered);
69、70は一行でいけそう @humuhimi

2021-06-01 10:19 UTC, ryuring commented on plugins/baser-core/src/Service/PluginsService.php
> +     * @noTodo
@humuhimi noTodoではない

2021-06-01 10:19 UTC, ryuring commented on plugins/baser-core/src/Service/PluginsService.php
> +        $available = $this->getAvailable();
@humuhimi getAvailableに、registered オプションを付けた方が早いかもですね。

2021-06-02 03:03 UTC, humuhimi commented on plugins/baser-core/src/Service/PluginsService.php
> +        $plugins = $sortMode ? $registered : array_merge($registered, $unregistered);
完了です

2021-06-02 03:03 UTC, humuhimi commented on plugins/baser-core/src/Controller/Admin/PluginsController.php
> +        $this->set('sortmode', $this->request->getQuery('sortmode'));
@ryuring 
直接参照するように変更しました！

2021-06-02 03:03 UTC, humuhimi commented on plugins/baser-core/src/Service/PluginsService.php
> +     * @noTodo
@noTodoとりあえず、消しました

2021-06-02 03:04 UTC, humuhimi commented on plugins/baser-core/src/Service/PluginsService.php
> +        $available = $this->getAvailable();
つけました！

2021-06-02 06:13 UTC, ryuring commented
@humuhimi あとテストですね。よろしくお願いします。

2021-06-02 06:25 UTC, humuhimi commented
@ryuring 
テスト完了しました。そもそも、getAvailableいらないですね。getIndexにまとめます

2021-06-02 07:22 UTC, merged

2021-06-02 07:22 UTC, ryuring commented
@humuhimi おつかれさまでした、マージします！