fix #1313 BcRedirectSubSiteFilter::process のユニットテスト実装
baserproject/ucmitz pull request #1420
Opened 2022-11-10 06:27 UTC by HungDV2022

2022-11-11 02:01 UTC, ryuring commented
@HungDV2022 
あと３つのテストをお願いします。
- リダイレクト先のサイトが非公開の場合はリダイレクトしない。
- クエリーパラメーターに、{$site->name}_auto_redirect=off と設定されている場合はリダイレクトしない。
- アップデーターや管理画面へのアクセスの場合には無視する。

アップデーター：/update
管理画面：/baser/admin

2022-11-11 07:20 UTC, HungDV2022 commented
@ryuring ユニットテストを調整しました
確認お願いします。

2022-11-14 08:18 UTC, ryuring requested changes

2022-11-14 08:18 UTC, ryuring commented on plugins/baser-core/tests/TestCase/Middleware/BcRedirectSubSiteFilterTest.php
> +        $request = $this->getRequest('/update');
@HungDV2022 RuntimeException が出るのは問題があるからです。
調べたところ、認証エラーになっていました。
次のコードで調整お願いします。
```
        $this->loadFixtureScenario(InitAppScenario::class);
        $request = $this->loginAdmin($this->getRequest('/update'));
        $this->_response = $this->BcRedirectSubSiteFilter->process($request, $this->Application);
        $this->assertResponseSuccess();
        $request = $this->loginAdmin($this->getRequest('/baser/admin'));
        $this->_response = $this->BcRedirectSubSiteFilter->process($request, $this->Application);
        $this->assertResponseSuccess();
```

2022-11-14 08:18 UTC, ryuring commented on plugins/baser-core/tests/TestCase/Middleware/BcRedirectSubSiteFilterTest.php
> +        $this->_response = $this->BcRedirectSubSiteFilter->process($request, $this->Application);
@HungDV2022 RuntimeException ではなく、`$this->assertResponseSuccess();` となるのが正解です。

2022-11-14 08:18 UTC, ryuring commented on plugins/baser-core/tests/TestCase/Middleware/BcRedirectSubSiteFilterTest.php
> +        $this->expectException(\RuntimeException::class);
@HungDV2022 RuntimeException ではなく、`$this->assertResponseSuccess();` となるのが正解です。

2022-11-15 05:53 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/Middleware/BcRedirectSubSiteFilterTest.php
> +            'name' => '',
@ryuring 
こちらを修正しました
確認お願いします。

2022-11-15 05:53 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/Middleware/BcRedirectSubSiteFilterTest.php
> +        $request = $this->getRequest('/about')->withParam('plugin', 'BaserCore')->withParam('controller', 'Pages')->withParam('action', 'view');
@ryuring 
こちらを修正しました
確認お願いします。

2022-11-15 05:53 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/Middleware/BcRedirectSubSiteFilterTest.php
> +        $request = $this->getRequest('/update');
@ryuring 
こちらを修正しました
確認お願いします。

2022-11-15 05:54 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/Middleware/BcRedirectSubSiteFilterTest.php
> +        $this->_response = $this->BcRedirectSubSiteFilter->process($request, $this->Application);
@ryuring 
こちらを修正しましたがエラーを出てしまったので修正方を教えていただけませんか。

2022-11-15 05:54 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/Middleware/BcRedirectSubSiteFilterTest.php
> +        $this->expectException(\RuntimeException::class);
@ryuring 
こちらを修正しましたがエラーを出てしまったので修正方を教えていただけませんか。

2022-11-17 03:57 UTC, HungDV2022 commented
@ryuring  ユニットテストを調整しました
確認お願いします。

2022-11-23 03:04 UTC, ryuring commented
@HungDV2022 難しいテストだったと思います。ありがとうございました。

2022-11-23 03:05 UTC, merged