Api/xxx controller
baserproject/ucmitz pull request #1427
Opened 2022-11-10 06:55 UTC by hiraokakoichi

@ryuring 
「Api/」から始まる１メソッドしかないコントローラがいくつかあったので、このブランチにまとめてヘッダーを書きました。ご確認をお願いします！

2022-11-10 07:44 UTC, ryuring requested changes
レビューいれています。 @hiraokakoichi

2022-11-10 07:44 UTC, ryuring commented on plugins/bc-blog/src/Controller/Api/BlogPostsController.php
> +     * ###エラー
非常に細かいですが、### と日本語の間に半角スペースをお願いします。

2022-11-10 07:44 UTC, ryuring commented on plugins/bc-blog/src/Controller/Api/BlogTagsController.php
> +     * ###エラー
こちらもお願いします。

2022-11-14 05:32 UTC, hiraokakoichi commented on plugins/bc-blog/src/Controller/Api/BlogPostsController.php
> +     * ###エラー
@ryuring 
申し訳ありません！修正しました！

2022-11-14 05:32 UTC, hiraokakoichi commented on plugins/bc-blog/src/Controller/Api/BlogTagsController.php
> +     * ###エラー
@ryuring 
こちらも修正しました！

2022-11-14 06:36 UTC, merged