fix #1415 Admin/BlogPostsController::publish のユニットテスト実装
baserproject/ucmitz pull request #1474
Opened 2022-11-17 05:52 UTC by HungDV2022

2022-11-23 02:25 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/Controller/Admin/BlogPostsControllerTest.php
> +        BlogPostFactory::make([
あと、こちらは、FixtureFactoryの、setDefaultTemplate をしっかり書いて、設定項目をへらすようにしましょうか。

```
    protected function setDefaultTemplate(): void
    {
        $this->setDefaultData(function (Generator $faker) {
            return [
                'blog_content_id' => $faker->randomNumber(),
                'no' => $faker->randomNumber(),
                'title' => $faker->title(),
                'content' => $faker->randomHtml(),
                'detail' => $faker->randomHtml(),
                'blog_category_id' => $faker->randomNumber(),
                'user_id'  => $faker->randomNumber(),
                'posted' => $faker->date(),
                'content_draft' => $faker->randomHtml(),
                'detail_draft' => $faker->randomHtml(),
                'publish_begin' => null,
                'publish_end' => null,
                'exclude_search' => $faker->randomElement([true, false]),
                'eye_catch' => null,
                'created' => $faker->date(),
                'modified' => $faker->date()
            ];
        });
    }
```

そうするとこんな感じで書けるかと、あまり大きな効果はないですが少しずつでもシンプルにしていきたいです。

```
BlogPostFactory::make([
            'id' => 1,
            'blog_content_id' => 2,
            'status' => false,
        ])->persist();
```
テストに関係のある項目だけに定義が絞れます。

2022-11-23 02:27 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/Controller/Admin/BlogPostsControllerTest.php
> +        BlogPostFactory::make([
さらに、Factoryに次のように定義するとテスト側はさらに簡単になりますね。

```php
    public function unpubish($id, $blogContentId)
    {
        return $this->setField('id', $id)
            ->setField('blog_content_id', $blogContentId)
            ->setField('status', false);
    }
```
こんな感じでかけます。
```php
BlogPostFactory::make()->unpubish(1, 1)->persist()
```

2022-11-24 05:44 UTC, HungDV2022 commented
@ryuring 
ユニットテストを調整しました
確認お願いします。

2022-11-25 07:28 UTC, ryuring requested changes

2022-11-25 07:28 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/Controller/Admin/BlogPostsControllerTest.php
> +        BlogPostFactory::make(['id' => 2, 'blog_content_id' => null])->persist();
blog_content_id を null にした理由を教えて下さい。 @HungDV2022

2022-11-25 07:28 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/Controller/Admin/BlogPostsControllerTest.php
> +            'id' => 1,
@HungDV2022 せっかく、 `unpubish`  を作ったので使いましょう。

2022-11-25 07:28 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/Controller/Admin/BlogPostsControllerTest.php
> +        $this->assertFlashMessage('ブログ記事「baser ブログのタイトル」を公開状態にしました。');
`unpubish` を利用することによって、タイトルがランダムになってテストができないのであれば、`assertRegExp` を利用しましょう。

```php
$this-> assertRegExp('/ブログ記事「.+」を公開状態にしました。/', $_SESSION['flash']['message']);
```

2022-11-30 00:29 UTC, HungDV2022 commented on plugins/bc-blog/tests/TestCase/Controller/Admin/BlogPostsControllerTest.php
> +        BlogPostFactory::make(['id' => 2, 'blog_content_id' => null])->persist();
テスト

2022-11-30 00:31 UTC, merged