fix #1545 ブログコメント削除API実装
baserproject/ucmitz pull request #1549
Opened 2022-11-28 10:56 UTC by zebeel

2022-11-30 00:37 UTC, ryuring requested changes
レビュー入れました、本体コードを調整の上、テストの方も調整してください。

2022-11-30 00:37 UTC, ryuring commented on plugins/bc-blog/src/Controller/Api/BlogCommentsController.php
> +        if ($this->request->is(['post', 'delete'])) {
@zebeel APIの場合はこちらを使ってください
```
$this->request->allowMethod(['post', 'put']);
```

2022-11-30 00:37 UTC, ryuring commented on plugins/bc-blog/src/Controller/Api/BlogCommentsController.php
> +                    $message = __d('baser', 'ブログコメント「{0}」を削除しました。', $blogComment->message);
コメントの削除のメッセージは、`message` でなく、`no` を参照してください。

Admin/BlogCommentsController::delete を参考にしてください。

2022-11-30 00:37 UTC, ryuring commented on plugins/bc-blog/src/Controller/Api/BlogCommentsController.php
> +                $message = __d('baser', 'データベース処理中にエラーが発生しました。');
@zebeel `PersistenceFailedException` の際のエラーメッセージは、`入力エラーです。内容を修正してください。` でお願いします。

それとはまた別に、 `BcException` でキャッチして、`データベース処理中にエラーが発生しました。` を使ってください。

2022-11-30 08:27 UTC, zebeel commented on plugins/bc-blog/src/Controller/Api/BlogCommentsController.php
> +                    $message = __d('baser', 'ブログコメント「{0}」を削除しました。', $blogComment->message);
@ryuring メッセージの内容はどこかのパターンを参考できますか？今回は `$blogComment->no` が正しいですが、別のControllerならどのフィルドが正しいかわかりません。

2022-11-30 08:47 UTC, ryuring commented on plugins/bc-blog/src/Controller/Api/BlogCommentsController.php
> +                    $message = __d('baser', 'ブログコメント「{0}」を削除しました。', $blogComment->message);
@zebeel Admin/BlogCommentsController::delete を参考にしてください。

2022-11-30 08:57 UTC, zebeel commented on plugins/bc-blog/src/Controller/Api/BlogCommentsController.php
> +                $message = __d('baser', 'データベース処理中にエラーが発生しました。');
@ryuring 
各種APIを参考するとやり方が統一しないですが修正したソースが大丈夫かを見てもらえないでしょうか？

2022-11-30 09:10 UTC, ryuring commented on plugins/bc-blog/src/Controller/Api/BlogCommentsController.php
> +                $message = __d('baser', 'データベース処理中にエラーが発生しました。');
@zebeel そうですね。やり方が統一されていないのが現状です。
ただ、`PersistenceFailedException` で拾えなかったエラーが発生した時に、問題が発生してしまうので、次のものを追加して、今後これで統一していきたいと思っています。

```php
            } catch (BcException $e) {
                $this->setResponse($this->response->withStatus(500));
                $message = __d('baser', 'データベース処理中にエラーが発生しました。' . $e->getMessage());
            }
```

2022-11-30 09:23 UTC, zebeel commented on plugins/bc-blog/src/Controller/Api/BlogCommentsController.php
> +                $message = __d('baser', 'データベース処理中にエラーが発生しました。');
@ryuring 
ご回答ありがとうございます。
ソースを修正しました。ご確認お願い致します。

2022-11-30 10:14 UTC, ryuring commented on plugins/bc-blog/src/Controller/Api/BlogCommentsController.php
> +                $message = __d('baser', 'データベース処理中にエラーが発生しました。');
@zebeel ごめんなさい、`BcException` では、全ての例外は拾えないことがわかりました。
`Throwable` に変更をお願いします。

2022-11-30 11:20 UTC, zebeel commented on plugins/bc-blog/src/Controller/Api/BlogCommentsController.php
> +                $message = __d('baser', 'データベース処理中にエラーが発生しました。');
@ryuring Throwable に変更しました。

2022-12-01 07:01 UTC, ryuring commented on plugins/bc-blog/src/Controller/Api/BlogCommentsController.php
> +                $message = __d('baser', 'データベース処理中にエラーが発生しました。');
@zebeel 修正ありがとうございました。

2022-12-01 07:01 UTC, merged