fix #1528 ブログ記事単一データ取得のAPI実装
baserproject/ucmitz pull request #1561
Opened 2022-12-02 03:18 UTC by HungDV2022

2022-12-05 08:32 UTC, HungDV2022 commented
@ryuring  
ContentLinksControllerにinitialize の allowUnauthenticatedを設定しいないので調整しました
確認お願いします。

2022-12-06 23:28 UTC, ryuring commented
> @ryuring ContentLinksControllerにinitialize の allowUnauthenticatedを設定しいないので調整しました 確認お願いします。

@HungDV2022 問題ないです

2022-12-06 23:33 UTC, ryuring requested changes

2022-12-06 23:33 UTC, ryuring commented on plugins/bc-blog/src/Controller/Api/BlogPostsController.php
> +        $queryParams = array_merge($queryParams, [
@HungDV2022 status の設定について、PagesControllerも間違っていましたので修正しました。 
https://github.com/baserproject/ucmitz/commit/1db52d690b60ee3c02575f01d80185e4549ee2d9
これだと、ログイン認証ができていてもstatus の変更ができません。
調整お願いします。

2022-12-06 23:33 UTC, ryuring commented on plugins/bc-blog/src/Controller/Api/BlogPostsController.php
> +            $blogPost = $e->getEntity();
@HungDV2022 BcException には、getEntity() メソッドは存在しません。Throwable に変更してエラー時にはメッセージを取得しましょう。

2022-12-06 23:33 UTC, ryuring commented on plugins/bc-content-link/src/Controller/Api/ContentLinksController.php
> +        } catch(BcException $e) {
@HungDV2022 ここもThrowable に変更お願いします。

2022-12-07 05:24 UTC, HungDV2022 commented on plugins/bc-blog/src/Controller/Api/BlogPostsController.php
> +        $queryParams = array_merge($queryParams, [
@ryuring こちらを調整しました。
確認お願いします。

2022-12-08 02:39 UTC, merged