fix #1535 ブログ記事の一括処理（公開、非公開、削除）のAPI実装
baserproject/ucmitz pull request #1596
Opened 2022-12-08 03:44 UTC by HungDV2022

2022-12-10 02:47 UTC, ryuring requested changes

2022-12-10 02:47 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/Controller/Api/BlogPostsControllerTest.php
> +        BlogPostFactory::make([
@HungDV2022 こういう時にこそ、`BlogPostFactory::unpubish` を使ってコード量を減らしてもらいたいです。
あと、`BlogPostFactory::pubish` も作りましょう。

2022-12-19 04:08 UTC, HungDV2022 commented on plugins/bc-blog/tests/TestCase/Controller/Api/BlogPostsControllerTest.php
> +        BlogPostFactory::make([
@ryuring 
こちらを修正しました。
確認お願いします。

2023-01-02 06:39 UTC, ryuring commented
@HungDV2022 `BlogPostFactory::pubish` は作られていませんでしたが、コード量は減っていましたのでマージします。

2023-01-02 06:39 UTC, merged