fix #1634 BlogHelper::getEyeCatch のユニットテスト実装
baserproject/ucmitz pull request #1655
Opened 2022-12-13 12:19 UTC by zebeel

2022-12-14 03:18 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
> +        // 特殊文字をエスケープするテスト
@zebeel Aタグを出力するメソッドは、セキュリティ上の問題から、全て escape の初期値を true する方針となりました。本体のコードの修正をお願いします。

2022-12-14 03:21 UTC, ryuring requested changes
１点、変更をお願いします

2022-12-14 09:37 UTC, zebeel commented on plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
> +        // 特殊文字をエスケープするテスト
@ryuring aタグが出力する場合、全てescape=trueを設定しました。

2022-12-14 10:05 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
> +        // 特殊文字をエスケープするテスト
@zebeel 本体コードの修正ができてないみたいですね。
plugins/bc-blog/src/View/Helper/BlogHelper.php の1186行目です。

2022-12-14 10:06 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/View/Helper/BlogHelperTest.php
> +        // 特殊文字をエスケープするテスト
@zebeel もう対応する時間的余裕がなければ僕がやっておきますので言ってください。

2023-01-02 06:43 UTC, ryuring commented
@zebeel マージしてこちらで調整しておきます。

2023-01-02 06:43 UTC, merged