fix #1611 BlogPostsService::get のユニットテスト実装
baserproject/ucmitz pull request #1747
Opened 2023-01-06 05:46 UTC by HungDV2022

2023-01-16 21:28 UTC, ryuring commented
@HungDV2022 次のテストを追加してください。

$options の status を publish として、レコードの status が true でないデータを指定する

publish を指定したとしても公開状態のデータでないため、エラーとなる事を確認しておきたいです。

2023-01-18 09:10 UTC, HungDV2022 commented
> @HungDV2022 次のテストを追加してください。
> 
> $options の status を publish として、レコードの status が true でないデータを指定する
> 
> publish を指定したとしても公開状態のデータでないため、エラーとなる事を確認しておきたいです

 @ryuring 
こちらがユニットテストを追加しました
確認お願いします。

2023-01-25 21:57 UTC, ryuring requested changes

2023-01-25 21:57 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/Service/BlogPostsServiceTest.php
> +    public function testGetddddd()
@HungDV2022 メソッド名が変になっちゃってますね

2023-01-25 21:57 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/Service/BlogPostsServiceTest.php
> +    public function testGetddddd()
あとは大丈夫です

2023-01-30 09:16 UTC, HungDV2022 commented on plugins/bc-blog/tests/TestCase/Service/BlogPostsServiceTest.php
> +    public function testGetddddd()
@ryuring すみません。こちらを修正しました。
確認お願いします。

2023-01-31 01:06 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/Service/BlogPostsServiceTest.php
> +    public function testGetddddd()
@HungDV2022 ありがとうございます〜

2023-01-31 01:06 UTC, merged