fix #1615 BlogPostsService::getIndexByCategory のユニットテスト実装
baserproject/ucmitz pull request #1760
Opened 2023-01-12 06:33 UTC by HungDV2022

2023-01-16 22:30 UTC, ryuring requested changes

2023-01-16 22:30 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/Service/BlogPostsServiceTest.php
> +        $this->assertInstanceOf(\Cake\ORM\Query::class, $result);
@HungDV2022 戻り値が Query かどうかは重要ではないです。削除お願いします。

2023-01-16 22:30 UTC, ryuring commented on plugins/bc-blog/tests/TestCase/Service/BlogPostsServiceTest.php
> +        $this->assertEquals('title 1', $blogPosts[0]->title);
@HungDV2022 テストメソッド内で、データ生成をしているので、データが２件取れている事が確認できれば、タイトルが一致しているかどうかは重要ではありません。602〜603も不要です。

2023-01-17 06:46 UTC, HungDV2022 commented on plugins/bc-blog/tests/TestCase/Service/BlogPostsServiceTest.php
> +        $this->assertInstanceOf(\Cake\ORM\Query::class, $result);
@ryuring 
こちらを削除しました。
確認お願いします。

2023-01-17 06:46 UTC, HungDV2022 commented on plugins/bc-blog/tests/TestCase/Service/BlogPostsServiceTest.php
> +        $this->assertEquals('title 1', $blogPosts[0]->title);
@ryuring 
こちらを削除しました。
確認お願いします。

2023-01-18 03:45 UTC, merged