fix #1771 テーマファイルAPI ファイル新規追加
baserproject/ucmitz pull request #1778
Opened 2023-01-16 09:13 UTC by HungDV2022

2023-01-16 23:10 UTC, ryuring requested changes

2023-01-16 23:10 UTC, ryuring commented on plugins/bc-theme-file/src/Controller/Api/ThemeFilesController.php
> +            $this->setResponse($this->response->withStatus(400));
@HungDV2022 `$e->getForm()->getErrors()` でエラーメッセージが取得できます。
$this->set() に渡してください。

2023-01-16 23:10 UTC, ryuring commented on plugins/bc-theme-file/src/Controller/Api/ThemeFilesController.php
> +            $message = __d('baser', '入力エラーです。内容を修正してください。' . $e->getMessage());
@HungDV2022 入力エラーではないので、「処理中にエラーが発生しました。」としてください。

2023-01-16 23:10 UTC, ryuring commented on plugins/bc-theme-file/tests/TestCase/Controller/Api/ThemeFilesControllerTest.php
> +        $this->assertEquals('/test-pathbase_name_1.html', $result->entity->fullpath);
@HungDV2022 実際にファイルが作成されいてるテストを追加してください。
また、そのファイルを削除する処理も必要です。

2023-01-17 08:34 UTC, HungDV2022 commented on tests/bootstrap.php
> +    ['plugin' => 'BcThemeFile'],
@ryuring 
ローカル環境でこちらがないと実装できませんので原因を調査お願いします。

2023-01-17 08:34 UTC, HungDV2022 commented on plugins/bc-theme-file/src/Controller/Api/ThemeFilesController.php
> +            $this->setResponse($this->response->withStatus(400));
@ryuring 
こちらを修正しました。
確認お願いします。

2023-01-17 08:34 UTC, HungDV2022 commented on plugins/bc-theme-file/src/Controller/Api/ThemeFilesController.php
> +            $message = __d('baser', '入力エラーです。内容を修正してください。' . $e->getMessage());
@ryuring
こちらを修正しました。
確認お願いします。

2023-01-17 08:35 UTC, HungDV2022 commented on plugins/bc-theme-file/tests/TestCase/Controller/Api/ThemeFilesControllerTest.php
> +        $this->assertEquals('/test-pathbase_name_1.html', $result->entity->fullpath);
@ryuring
こちらを修正しました。
確認お願いします。

2023-01-17 08:38 UTC, HungDV2022 commented on plugins/bc-theme-file/tests/TestCase/Controller/Api/ThemeFilesControllerTest.php
> +        $this->assertEquals('処理中にエラーが発生しました。', $result->message);
<img width="1240" alt="スクリーンショット 2023-01-17 15 35 34" src="https://user-images.githubusercontent.com/110375578/212848673-b246d55e-510b-440a-bc90-50d6ac408da3.png">
 @ryuring コンテンツがない場合は画像のようにエラーが出てしまったので本家のコードを修正必要でしょうか。

2023-01-18 03:48 UTC, ryuring commented on plugins/bc-theme-file/tests/TestCase/Controller/Api/ThemeFilesControllerTest.php
> +        $this->assertEquals('処理中にエラーが発生しました。', $result->message);
あ、そうですね。修正をお願いしてもいいですか？ @HungDV2022

2023-01-18 03:48 UTC, ryuring commented on tests/bootstrap.php
> +    ['plugin' => 'BcThemeFile'],
@HungDV2022 了解です、マージした後に確認しますね。

2023-01-18 09:13 UTC, HungDV2022 commented on plugins/bc-theme-file/tests/TestCase/Controller/Api/ThemeFilesControllerTest.php
> +        $this->assertEquals('処理中にエラーが発生しました。', $result->message);
@ryuring 
こちらを修正してみました。
確認お願いします。

2023-01-25 21:58 UTC, merged