fix #1775 テーマファイルAPI ファイルを表示
baserproject/ucmitz pull request #1786
Opened 2023-01-20 03:42 UTC by HungDV2022

2023-02-06 06:28 UTC, ryuring commented on plugins/bc-theme-file/src/Controller/Api/ThemeFilesController.php
> +    public function view(ThemeFilesAdminServiceInterface $service)
@HungDV2022 xxxAdminService は、APIで利用する事を想定していません。ThemeFilesService を利用してください。

2023-02-06 06:30 UTC, ryuring commented on plugins/bc-theme-file/src/Controller/Api/ThemeFilesController.php
> +            'themeFile' => $themeFile ?? null,
@HungDV2022 $themeFile ではなく、$entity を返却する仕様としてください。

2023-02-06 06:31 UTC, ryuring requested changes
変更をお願いします

2023-02-07 08:59 UTC, HungDV2022 commented on plugins/bc-theme-file/src/Controller/Api/ThemeFilesController.php
> +            'themeFile' => $themeFile ?? null,
こちらを修正しました。
確認お願いします。

2023-02-08 23:53 UTC, merged