ThemesController　APIのステータスをチェック
baserproject/ucmitz pull request #1878
Opened 2023-02-27 07:05 UTC by HungDV2022

2023-03-02 03:11 UTC, ryuring requested changes

2023-03-02 03:11 UTC, ryuring commented on plugins/baser-core/src/Controller/Api/ThemesController.php
> +        } catch (PersistenceFailedException $e) {
@HungDV2022 PersistenceFailedException は発生しませんので削除して大丈夫です。

2023-03-02 03:11 UTC, ryuring commented on plugins/baser-core/src/Controller/Api/ThemesController.php
> +            } catch (PersistenceFailedException $e) {
@HungDV2022 PersistenceFailedException は発生しませんので削除して大丈夫です。

2023-03-04 07:45 UTC, ryuring requested changes

2023-03-04 07:45 UTC, ryuring commented on plugins/baser-core/src/Controller/Api/ThemesController.php
> +        } catch (RecordNotFoundException $e) {
@HungDV2022 テーマはDBデータではなくフォルダでしたので、RecordNotFoundException 発生しませんでした。削除お願いします。

2023-03-04 07:45 UTC, ryuring commented on plugins/baser-core/src/Controller/Api/ThemesController.php
> +        } catch (PersistenceFailedException $e) {
@HungDV2022 テーマはDBデータではなくフォルダでしたので、PersistenceFailedException 発生しませんでした。削除お願いします。

2023-03-04 07:45 UTC, ryuring commented on plugins/baser-core/src/Controller/Api/ThemesController.php
> +        } catch (RecordNotFoundException $e) {
@HungDV2022 テーマはDBデータではなくフォルダでしたので、RecordNotFoundException 発生しませんでした。削除お願いします。

2023-03-04 07:45 UTC, ryuring commented on plugins/baser-core/src/Controller/Api/ThemesController.php
> +        } catch (RecordNotFoundException $e) {
@HungDV2022 ここは、sites テーブルにアクセスしますので、このままで大丈夫です。

2023-03-04 08:46 UTC, HungDV2022 commented
@ryuring 
こちらを修正しました。
確認お願いします。

2023-03-04 10:04 UTC, ryuring commented on plugins/baser-core/src/Controller/Api/ThemesController.php
> +        } catch (RecordNotFoundException $e) {
@HungDV2022 あああ、削除してしまってるのね、、、こっちで戻しておきますね。

2023-03-04 10:06 UTC, merged