ContentFoldersControllerのindex メソッドのcontain を見直す
baserproject/ucmitz pull request #2073
Opened 2023-03-15 02:35 UTC by HungDV2022

2023-03-15 22:19 UTC, ryuring commented
@HungDV2022 ごめんなさい、他の件で問題が出たので僕の方でも同じ場所を変更していてコンフリクトしたようです。一度コンフリクトを解消してもらえますか？

2023-03-16 00:04 UTC, HungDV2022 commented
@ryuring 
コンフリクトを解消しました。確認お願いします。

2023-03-16 05:27 UTC, ryuring commented on plugins/baser-core/src/Service/ContentFoldersService.php
> +            'Contents' => null,
@HungDV2022 デフォルトを `['Contents'] ` にしてくだしあ。Webアプリ側で問題が発生する可能性があります。

2023-03-16 05:29 UTC, ryuring requested changes
レビュー入れています。

キーがおかしいです。

2023-03-19 08:51 UTC, merged