MailFieldsController ゲストアクセスの条件を見直す
baserproject/ucmitz pull request #2169
Opened 2023-03-23 04:05 UTC by HungDV2022

2023-03-24 00:34 UTC, ryuring requested changes

2023-03-24 00:34 UTC, ryuring commented on plugins/bc-mail/src/Service/MailFieldsService.php
> +            $conditions = $this->MailFields->MailContents->Contents->getConditionAllowPublish();
@HungDV2022 `MailFields` 自体も `status` を持っていますのでそちらを追加してください。
https://docs.google.com/spreadsheets/d/1YT5PuZQdDNU0wrZdqYbh74KuLSw1SIt4_EKwPWOfDKA/edit#gid=1129992221&range=N152

2023-03-24 00:34 UTC, ryuring commented on plugins/bc-mail/src/Service/MailFieldsService.php
> +            $query->where($this->MailFields->MailContents->Contents->getConditionAllowPublish());
@HungDV2022 `MailFields` 自体も `status` を持っていますのでそちらを追加してください。
https://docs.google.com/spreadsheets/d/1YT5PuZQdDNU0wrZdqYbh74KuLSw1SIt4_EKwPWOfDKA/edit#gid=1129992221&range=N153

2023-03-24 03:41 UTC, HungDV2022 commented on plugins/bc-mail/src/Service/MailFieldsService.php
> +            $conditions = $this->MailFields->MailContents->Contents->getConditionAllowPublish();
@ryuring 
https://docs.google.com/spreadsheets/d/1GD5JoFF2u-2KZPPNKL8HjYG2obNxFO-ES8n2gh-_d5E/edit?usp=sharing
MailFieldsテーブルの定義を見るとstatusが存在しないみたいです。

2023-03-24 10:19 UTC, ryuring commented on plugins/bc-mail/src/Service/MailFieldsService.php
> +            $conditions = $this->MailFields->MailContents->Contents->getConditionAllowPublish();
@HungDV2022 `use_field` を使ってください。
https://docs.google.com/spreadsheets/d/1GD5JoFF2u-2KZPPNKL8HjYG2obNxFO-ES8n2gh-_d5E/edit#gid=2127082121

2023-03-24 12:39 UTC, HungDV2022 commented on plugins/bc-mail/src/Service/MailFieldsService.php
> +            $conditions = $this->MailFields->MailContents->Contents->getConditionAllowPublish();
こちらを修正しました。確認お願いします。

2023-03-24 12:39 UTC, HungDV2022 commented on plugins/bc-mail/src/Service/MailFieldsService.php
> +            $query->where($this->MailFields->MailContents->Contents->getConditionAllowPublish());
こちらを修正しました。確認お願いします。

2023-03-28 23:39 UTC, ryuring commented on plugins/bc-mail/src/Service/MailFieldsService.php
> +            $query->where($this->MailFields->MailContents->Contents->getConditionAllowPublish());
@HungDV2022 ダメではないですが、このメソッドにおいて、$conditions を使って、where() を作るという意図に合っていないので気持ち悪い気がしますがいかがでしょう？

2023-03-30 03:07 UTC, HungDV2022 commented on plugins/bc-mail/src/Service/MailFieldsService.php
> +            $query->where($this->MailFields->MailContents->Contents->getConditionAllowPublish());
@ryuring 
修正しました。確認お願いします。

2023-03-31 01:14 UTC, ryuring commented on plugins/bc-mail/src/Service/MailFieldsService.php
> +            array_merge($conditions, $this->MailFields->MailContents->Contents->getConditionAllowPublish());
@HungDV2022 array_merge は参照渡しではないので、$conditions に影響がないです。

2023-03-31 06:30 UTC, HungDV2022 commented on plugins/bc-mail/src/Service/MailFieldsService.php
> +            array_merge($conditions, $this->MailFields->MailContents->Contents->getConditionAllowPublish());
@ryuring 
こちらを修正しました。
確認お願いします。

2023-03-31 08:09 UTC, merged