カスタムコンテンツプラグインのAPI設計書を書いたときコードを調整
baserproject/ucmitz pull request #2242
Opened 2023-04-06 11:54 UTC by HungDV2022

2023-04-09 00:55 UTC, ryuring requested changes

2023-04-09 00:55 UTC, ryuring commented on plugins/bc-custom-content/src/Service/CustomContentsService.php
> +            'status' => '',
@HungDV2022 認証なしのコントローラーなので、`publish` を設定してください

2023-04-09 00:55 UTC, ryuring commented on plugins/bc-custom-content/src/Controller/Api/Admin/CustomEntriesController.php
> +    public function add(CustomEntriesServiceInterface $service, $customTableId)
こちらは、RESTfull API に対応するため、元の引数に戻してください @HungDV2022

2023-04-09 00:55 UTC, ryuring commented on plugins/bc-custom-content/src/Service/CustomContentsService.php
> +            'status' => '',
@HungDV2022 設計書にも影響があると思います。よろしくお願いします。

2023-04-09 00:56 UTC, ryuring commented on plugins/bc-custom-content/src/Service/CustomContentsService.php
> +            'status' => '',
https://baserproject.github.io/5/web_api/baser_admin_api/bc-custom-content/custom_entries/add

2023-04-10 04:19 UTC, HungDV2022 commented on plugins/bc-custom-content/src/Service/CustomContentsService.php
> +            'status' => '',
@ryuring 
publish を追加しました。
確認お願いします。

2023-04-10 04:21 UTC, HungDV2022 commented on plugins/bc-custom-content/src/Controller/Api/Admin/CustomEntriesController.php
> +    public function add(CustomEntriesServiceInterface $service, $customTableId)
@ryuring こちらを修正しました。確認お願いします。

2023-04-10 04:22 UTC, HungDV2022 commented on plugins/bc-custom-content/plugins/BcCcFile/src/Event/BcCcFileControllerEventListener.php
> +        if(!$this->isAction('add', false) && !$this->isAction('edit', false)) return;
@ryuring 小文字に変更しました。

2023-04-10 10:40 UTC, ryuring commented on plugins/bc-custom-content/plugins/BcCcFile/src/Event/BcCcFileControllerEventListener.php
> +        if(!$this->isAction('add', false) && !$this->isAction('edit', false)) return;
@HungDV2022 この件、`plugins/bc-custom-content/plugins/BcCcFile/src/Event/BcCcFileControllerEventListener.php` が継承する `BcEventListener::getAction` で、キャメルケースに変換されているので、小文字にする必要はないと思いますが、動作しないなど理由がありましたか？

2023-04-10 11:51 UTC, HungDV2022 commented on plugins/bc-custom-content/plugins/BcCcFile/src/Event/BcCcFileControllerEventListener.php
> +        if(!$this->isAction('add', false) && !$this->isAction('edit', false)) return;
@ryuring 
大文字だとユニットテストだと動けましたがAPI Testerでテストしたらエラーが表示されます。
```
{
    "message": "BcCcFile\\Event\\BcCcFileControllerEventListener::setupUploader(): Argument #1 ($tableId) must be of type int, null given, called in /var/www/html/plugins/bc-custom-content/plugins/BcCcFile/src/Event/BcCcFileControllerEventListener.php on line 61",
    "url": "/baser/api/admin/bc-custom-content/custom_entries/add.json?custom_table_id=1",
    "code": 500,
    "file": "/var/www/html/plugins/bc-custom-content/plugins/BcCcFile/src/Event/BcCcFileControllerEventListener.php",
    "line": 89
}

```

2023-04-10 11:59 UTC, HungDV2022 commented on plugins/bc-custom-content/plugins/BcCcFile/src/Event/BcCcFileControllerEventListener.php
> +        if(!$this->isAction('add', false) && !$this->isAction('edit', false)) return;
恐らく行59にIF文が間違っているようです。
`if ($this->isAction('Add') || !$this->isAction('Edit')) return;`
こちらは如何でしょうか。

2023-04-11 00:27 UTC, ryuring commented on plugins/bc-custom-content/plugins/BcCcFile/src/Event/BcCcFileControllerEventListener.php
> +        if(!$this->isAction('add', false) && !$this->isAction('edit', false)) return;
@HungDV2022 動作確認しました。if 文は間違っていないですね。Add と Edit の場合に $this->setupUploader() を実行しなければなりません。次のようにお願いします。

```
    public function bcCustomContentCustomEntriesStartup(EventInterface $event)
    {
        $request = $event->getSubject()->getRequest();
        if(!$this->isAction('Add', false) && !$this->isAction('Edit', false)) return;
        $tableId = $request->getParam('pass.0');
        if(!$tableId) $tableId = $request->getQuery('custom_table_id');
        $this->setupUploader($tableId);
    }
```

2023-04-11 00:28 UTC, ryuring commented on plugins/bc-custom-content/plugins/BcCcFile/src/Event/BcCcFileControllerEventListener.php
> +        if(!$this->isAction('add', false) && !$this->isAction('edit', false)) return;
@HungDV2022 また、他のところでもエラーが出ました。
plugins/bc-custom-content/src/Model/Table/CustomEntriesTable.php の 537行目に次のように行を追加してください。

```php
    public function findAll(Query $query, array $options = []): Query
    {
        return $query->formatResults(function(\Cake\Collection\CollectionInterface $results) {
            return $results->map(function($row) {
                if(!is_object($row) || !method_exists($row, 'toArray')) return $row;
                $rowArray = $row->toArray();
                foreach($rowArray as $key => $value) {
                    if (is_string($value) && $this->isJson($value)) {
                        $row->{$key} = json_decode($value, true);
                    }
                }
                return $row;
            });
        });
    }
```

2023-04-11 02:12 UTC, HungDV2022 commented on plugins/bc-custom-content/plugins/BcCcFile/src/Event/BcCcFileControllerEventListener.php
> +        if(!$this->isAction('add', false) && !$this->isAction('edit', false)) return;
@ryuring 
ありがとうございます。
修正しましたので確認お願いします。

2023-04-11 03:09 UTC, ryuring commented
@HungDV2022 ありがとうございます、マージしますね。

2023-04-11 03:09 UTC, merged