testIsSuperUser追加その他微修正
baserproject/ucmitz pull request #41
Opened 2021-02-22 07:09 UTC by humuhimi

testIsSuperUser追加に伴い、UserGroupsFixtureとUsersFixtureとUsersUserGroupsFixtureにテスト用のレコードを追加しました。
また、影響が生じる範囲を微修正しました。

testAddの名前とメールアドレスがDB保存時のルールに沿ってないので、通るように変更しました。

確認お願いします。

2021-02-23 05:26 UTC, ryuring requested changes
@humuhimi レビュー入れました。調整お願いします。

2021-02-23 05:26 UTC, ryuring commented on plugins/baser-core/tests/TestCase/Controller/UsersControllerTest.php
> +            'email' => 'test@catchup.co.jp',
@humuhimi うちの会社のドメインはNGですw
`test@example.com` などにしましょう

2021-02-23 05:26 UTC, ryuring commented on plugins/baser-core/tests/TestCase/Utility/BcUtilTest.php
> +            $session = Router::getRequest()->getSession();
@humuhimi `Router`を使わなくても94行目で `Request` は取得できるのでは？

2021-02-23 05:26 UTC, ryuring commented on plugins/baser-core/tests/TestCase/Utility/BcUtilTest.php
> +        $expects = getenv('INSTALL_MODE');
@humuhimi `putenv` で切り替えれるかを確認するテストがよいかもですね

2021-02-24 01:52 UTC, humuhimi commented
全体修正して、またプルリク送ります！

2021-02-26 04:48 UTC, merged

2021-02-26 04:48 UTC, ryuring commented
@humuhimi ありがとうございます！マージしました