BcAuthHelperTest追加
baserproject/ucmitz pull request #42
Opened 2021-03-08 09:59 UTC by humuhimi

BcAuthHelperTest追加しました確認お願いします。
まだテストなれてないので、変な事してる可能性があるので厳し目にチェックお願いします！

2021-03-09 01:33 UTC, ryuring commented
@humuhimi PHP7.3 のテストが失敗してるようやね、一回見てもらえますか？わからなかったら相談してください。

2021-03-12 00:14 UTC, ryuring reviewed
@humuhimi レビュー終わりました。よろしくお願いします。

2021-03-12 00:14 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcAuthHelperTest.php
> +    public function testGetCurrentLoginUrl()
コードを見ると、`Configure::read('BcPrefixAuth.loginAction')` を参照しているようですので、この値を書き換えると、`testGetCurrentLoginUrl` の結果が変わるというテストも追加しておきましょうか。

2021-03-12 00:14 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcAuthHelperTest.php
> +     * FIXME:getCurrentUserPrefixSettings改修後にテストも改修必
@todo でアノテーションで反応するようにしておきましょう。

2021-03-12 00:14 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcAuthHelperTest.php
> +        $this->assertEquals(['admin'],$result);
細かいですが、カンマの後ろに半角スペースを入れましょう

2021-03-12 00:14 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcAuthHelperTest.php
> +     *@return void
@の前にスペース入れて！

2021-03-12 00:14 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcAuthHelperTest.php
> +     *@return void
こっちもスペースいれて！

2021-03-12 00:14 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcAuthHelperTest.php
> +     *@return void
ほかもよろしく

2021-03-12 00:14 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcAuthHelperTest.php
> +        $result = $this->BcAuth->isCurrentUserAdminAvailable();
その他の処理も書きたいところですが、内部的に依存している `getCurrentUserPrefixSettings` が、未実装なので、こちらも @todo を入れておきましょうか。

2021-03-12 00:14 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcAuthHelperTest.php
> +    public function testGetCurrentLogoutUrl()
こちらも `testGetCurrentLoginUrl` 同様、結果が変わるテストも。

2021-03-12 00:14 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcAuthHelperTest.php
> +        $result = $this->BcAuth->getCurrentLogoutUrl();
`Redirect` だよね。テスト内容が違う

2021-03-12 00:14 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcAuthHelperTest.php
> +        // ログインしない場合;
ログインしない場合は不要かな。ログインしているユーザーによって結果が変わるテストにしたいです。

2021-03-12 00:14 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcAuthHelperTest.php
> +                        ->contain(['UserGroups'])
インデント合わせてー

2021-03-12 00:14 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcAuthHelperTest.php
> +        $result = $this->BcAuth->isSuperUser();
データプロバイダーにまとめられそうですね。

2021-03-12 00:14 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcAuthHelperTest.php
> +            $request = $this->BcAdminAppView->getRequest();
request は、`$this->getRequest` でとってよさそう

2021-03-12 00:14 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcAuthHelperTest.php
> +    public function testIsAgentUser($id,$expected)
ログインするID と、Agentの IDは分けた方がよさそう。
代理ログインの仕様は、最初にログインしたユーザーから別のユーザーに切り替えることなので。
なので、`$this->loginAdmin` で設定するユーザーと、セッションで書き込むユーザーは別がいい。
`$this->loginAdmin($id)`は、1決め打ちでもいいんじゃないかと。

2021-03-12 00:14 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcAuthHelperTest.php
> +            [1,true],
全体的に、カンマの後ろには半角スペースを入れましょう。

2021-03-15 08:58 UTC, humuhimi commented
@ryuring 
遅れました！。修正完了しました確認お願いします！

2021-03-16 03:59 UTC, ryuring commented
https://github.com/baserproject/ucmitz/pull/42#discussion_r592820729

こちらの件、たぶん仕様を理解していない気がします。
一度時間作って話しましょうか。

2021-03-16 03:59 UTC, ryuring requested changes

2021-03-16 03:59 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcAuthHelperTest.php
> +        $result = $this->BcAuth->isCurrentUserAdminAvailable();
@humuhimi @todo をお願いします。

```
@todo getCurrentUserPrefixSettings() の実装が完了したら別パターンのテストを追加する
```

2021-03-16 03:59 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcAuthHelperTest.php
> +    public function testGetCurrentLogoutUrl()
@humuhimi こちら未対応ですね

2021-03-16 03:59 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcAuthHelperTest.php
> +        // ログインしない場合;
@humuhimi こちらも未対応みたいですね。

2021-03-16 03:59 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcAuthHelperTest.php
> +     * @todo getCurrentUserPrefixSettings改修後にテストも改修必
@humuhimi todo は return の下にお願いします。

2021-03-16 03:59 UTC, ryuring commented
@humuhimi 再レビューを入れました。よろしくお願いします。

2021-03-16 07:28 UTC, humuhimi commented
@ryuring 

- testGetCurrentUserPrefixSettingsのtodo位置変更、文言変更
- testGetCurrentLogoutUrl　ログアウトURL変更した場合の追加
- testGetCurrentLoginRedirectUrl　認証後リダイレクト先URLを変更した場合の追加
- testGetCurrentLoginUser id=1,2それぞれの場合のチェック追加
- testIsAgentUser　セッションが書かれているかどうかのテストに変更

上記修正しましたので、確認お願いします！

2021-03-17 01:10 UTC, merged

2021-03-17 01:11 UTC, ryuring commented
@humuhimi ありがとうございます、マージしました。