Bc admin helper test test search
baserproject/ucmitz pull request #45
Opened 2021-03-18 06:45 UTC by humuhimi

@ryuring 
devから個別にブランチ分けて再プルリク送りました。
お手数かけます！

BcAdminHelperTestのtestSearch確認お願いします。

2021-03-25 08:16 UTC, ryuring requested changes
@humuhimi レビュー入れました。よろしくお願いします。

2021-03-25 08:16 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcAdminHelperTest.php
> +            $SearchOpenedSaveUrl = '/baser/admin/Utilities/ajax_save_search_box';
search() メソッド側もアッパーになっているみたいだけどそっちがミスっぽいです。

2021-03-25 08:16 UTC, ryuring commented on plugins/baser-core/tests/TestCase/View/Helper/BcAdminHelperTest.php
> +            $this->BcAdmin->getView()->set('search', $template);
164〜171行まで、search() の内部的な処理をそのまま書いているのであまり意味がないです。

出力されたHTMLを正規表現で引っ掛けるぐらいで大丈夫ですよ。
こんな感じとか。
`'/class="bca-search">.+?<form/'`

2021-03-26 07:37 UTC, humuhimi commented
@ryuring 
修正追加しました確認お願いします！
以前router設定しないと通らなかったのですが、今回通るのはUtilitesをutilitiesにしたからですかね汗
コードめっちゃ短くなって助かりました笑

2021-03-29 02:25 UTC, merged

2021-03-29 02:26 UTC, ryuring commented
@ryuring 確認してマージしました！