cache clear実装
baserproject/ucmitz pull request #66
Opened 2021-04-05 09:41 UTC by humuhimi

時間かかってしまってすみません。
一旦、キャッシュクリア実装しましたがviewやdatasのキャッシュクリア含まれてません。
一度確認お願いします。

2021-04-07 01:44 UTC, ryuring requested changes
@humuhimi レビュー済です。調整お願いします。

2021-04-07 01:44 UTC, ryuring commented on plugins/baser-core/src/Controller/Admin/BcAdminAppController.php
> +    /**
@humuhimi インデントー

2021-04-07 01:44 UTC, ryuring commented on plugins/baser-core/src/basics.php
> -			clearCache(strtolower(Inflector::slug($url)), 'views', $ext);
clearViewCacheはまだ利用しない前提にする

2021-04-07 01:44 UTC, ryuring commented on plugins/baser-core/src/basics.php
> +function clearCache($params = null, $type = 'views', $ext = '.php') {
削除する

2021-04-07 01:44 UTC, ryuring commented on plugins/baser-core/src/Controller/Admin/UtilitiesController.php
> +        Cache::clear('_cake_core_');
clearAllCache で実装して欲しい

clearAllCache は、BcUtilに持っていく

2021-04-08 05:13 UTC, humuhimi commented on plugins/baser-core/src/Controller/Admin/BcAdminAppController.php
> +    /**
@ryuring 
修正しました！確認お願いします

2021-04-08 05:15 UTC, humuhimi commented
@ryuring
修正しました！確認お願いします

2021-04-08 09:04 UTC, ryuring requested changes
@humuhimi 概ねOKだけどあと少し調整をお願いします。

インデントがところどころ崩れているけど editorconfig 設定してますか？？

2021-04-08 15:51 UTC, humuhimi commented on plugins/baser-core/src/Controller/Admin/BcAdminAppController.php
> +     * @checked
editor config入れてます。
ただ、ところどころ移植したコードがうまく行かない場合があるので、vscodeのコマンド"convert indentation to Space"で再度全体変換するようにします。

2021-04-09 00:01 UTC, ryuring requested changes

2021-04-09 00:01 UTC, ryuring commented on plugins/baser-core/src/Utility/BcUtil.php
> +        // viewキャッシュ削除
@humuhimi 面倒だけどこういうことね
```
// TODO viewキャッシュ削除
```

2021-04-09 00:01 UTC, ryuring commented
@humuhimi 意識合わせのため、もうちょっと修正につきあってください。

2021-04-09 02:12 UTC, humuhimi commented
@ryuring 
なるほど！承知しました！

2021-04-09 02:22 UTC, humuhimi commented
vscodeだとTODO: でハイライトされるのこれで一旦プッシュしました。
大丈夫でしょうか？

2021-04-09 02:38 UTC, ryuring commented
@humuhimi 完璧です！マージします。

2021-04-09 02:38 UTC, merged