代理ログイン修正
baserproject/ucmitz pull request #67
Opened 2021-04-06 03:26 UTC by humuhimi

代理ログイン修正完了しました。
![image](https://user-images.githubusercontent.com/35215680/113654687-f1d8a780-96ca-11eb-86c8-e02b26471d06.png)

2021-04-07 02:01 UTC, ryuring requested changes
@humuhimi レビューいれました

2021-04-07 02:01 UTC, ryuring commented on plugins/baser-core/src/View/Helper/BcBaserHelper.php
>      public function isAdminUser($userGroupId = null)
引数を user エンティティに変更（仕様変更）

全てのコードを走査して他の利用箇所についても同樣の処理とする

2021-04-10 16:47 UTC, humuhimi commented
@ryuring 
完了しました。一度確認お願いします

2021-04-12 08:05 UTC, ryuring commented
@humuhimi 一個修正あってコンフリクトもしてたので、ローカルで squash でマージしました。
https://github.com/baserproject/ucmitz/commit/f7c74768674f9891bb1982953fd10f624c95dc7c

squashだと手柄の横取りになっちゃうのね、ごめん、、、

squashじゃないとコミットログ荒れるし悩ましいな

2021-04-12 08:05 UTC, closed without merging

2021-04-12 08:09 UTC, humuhimi commented
@ryuring 
承知しました！