fix #692 BcValidation::fileCheck() のユニットテスト
baserproject/ucmitz pull request #701
Opened 2022-08-02 09:49 UTC by Mkk818

phpunitでテストはしていますがエラーあり(Too few arguments to function)

2022-08-03 02:10 UTC, ryuring commented
@Mkk818 アノテーションのインポートができてないんだと思います。
[https://baserproject.github.io/5/ucmitz/regulation/migration_rule#%E3%82%B3%E3%83%BC%E3%83%89%E7%A7%BB%E8[…]3%9E%E3%83%BC%E3%82%AD%E3%83%B3%E3%82%B0](https://baserproject.github.io/5/ucmitz/regulation/migration_rule#%E3%82%B3%E3%83%BC%E3%83%89%E7%A7%BB%E8%A1%8C%E6%99%82%E3%81%AE%E3%83%9E%E3%83%BC%E3%82%AD%E3%83%B3%E3%82%B0)

2022-08-03 02:10 UTC, ryuring commented
```
use BaserCore\Annotation\UnitTest;
use BaserCore\Annotation\NoTodo;
use BaserCore\Annotation\Checked;
```

2022-08-03 03:51 UTC, Mkk818 commented
BcValidation.phpに記述があったので大丈夫かと思ったのですが、他のところで記述が必要でしょうか？

2022-08-03 07:47 UTC, ryuring requested changes

2022-08-03 07:47 UTC, ryuring commented on plugins/baser-core/tests/TestCase/Model/Validation/BcValidationTest.php
> +     * @checked
@Mkk818 細かく確認しました。

アノテーションを入れるのは、BcValidationTest ではなく、BcValidation の方となります。
テストのファイルには、アノテーションは入れてはいけません、今回のエラーとなります。

2022-08-04 01:59 UTC, ryuring commented
@Mkk818 テストが失敗してしまってますね。確認お願いします。

2022-08-04 02:12 UTC, Mkk818 commented on plugins/baser-core/tests/TestCase/Model/Validation/BcValidationTest.php
> +    public function testFileCheck($fileName, $fileSize, $errorCode, $expect)
@ryuring
https://github.com/baserproject/ucmitz/runs/7664028600?check_suite_focus=true#step:6:43
で

BaserCore\Test\TestCase\Model\Validation\BcValidationTest::testFileCheck
ArgumentCountError: Too few arguments to function BaserCore\Test\TestCase\Model\Validation\BcValidationTest::testFileCheck(),
とエラーが出ていて、ここの引数が足りないのが原因とありますが、
中で他に定義するべきものがあるということでしょうか？
追記：XDEBUGは出なくなりました。ありがとうございます。

2022-08-04 02:14 UTC, Mkk818 commented
@ryuring
https://github.com/baserproject/ucmitz/runs/7664028600?check_suite_focus=true#step:6:43
で

BaserCore\Test\TestCase\Model\Validation\BcValidationTest::testFileCheck
ArgumentCountError: Too few arguments to function BaserCore\Test\TestCase\Model\Validation\BcValidationTest::testFileCheck(),
とエラーが出ていて、ここの引数が足りないのが原因とありますが、
plugins/baser-core/tests/TestCase/Model/Validation/BcValidationTest.php
中で他に定義するべきものがあるということでしょうか？
追記：XDEBUGは出なくなりました。ありがとうございます。

2022-08-08 03:26 UTC, ryuring requested changes

2022-08-08 03:26 UTC, ryuring commented on plugins/baser-core/tests/TestCase/Model/Table/_NotYetMigrated/BcAppTest.php
> +
@Mkk818 ここ、関数が途切れた形になってしまってますね。

2022-08-08 03:26 UTC, ryuring commented on plugins/baser-core/src/Model/Validation/BcValidation.php
> +
186行目、余計な空白行が入っています。削除してください。 @Mkk818

2022-08-08 03:26 UTC, ryuring commented
@Mkk818 テストが失敗しています。コメントを入れてますのでご確認ください。

2022-08-12 00:47 UTC, ryuring commented
@Mkk818 この件、こちらのコミットで解決していますのでクローズします
https://github.com/baserproject/ucmitz/commit/5cc6ed3efed9edd8570542581bbf170f8f14fb3b

2022-08-12 00:47 UTC, closed without merging