fix #809 SearchIndexesAdminService::getViewVarsForIndex()のユニットテスト
baserproject/ucmitz pull request #820
Opened 2022-08-25 06:17 UTC by HungDV2022

2022-08-25 11:18 UTC, ryuring commented
@HungDV2022 SearchIndexesAdminService::getViewVarsForIndex() について仕様変更を行いましたので、それに合わせてテストを調整してください。お手数おかけします。

2022-08-25 11:58 UTC, HungDV2022 commented
@ryuring 
テストの調整しました
確認お願いします

2022-08-25 12:50 UTC, ryuring commented
BcAdminHelperTest::testSetTitle() の仕様が変わったのでテストが失敗してます。
こちらも調整をお願いしていいですか？
@HungDV2022

2022-08-25 12:56 UTC, HungDV2022 commented
@ryuring 
テストの調整しました
確認お願いします

2022-08-25 13:09 UTC, HungDV2022 commented
@ryuring 
ローカルでBcUpdateFilterMiddlewareTest::test_proccessNormal()を実行してみましたが問題ないでした
私の方でテストを再実行できないので確認お願いします。

2022-08-27 02:34 UTC, ryuring commented on plugins/bc-search-index/tests/TestCase/Service/SearchIndexesAdminServiceTest.php
> +    protected $fixtures = [
@HungDV2022 CakePHP4.3 から FixtureManager によるフィクスチャの利用が非推奨になったため、新しいテストについては、FixtureFactory を利用していきたいです。

■ CakePHPドキュメント
https://book.cakephp.org/4/ja/development/testing.html#id20
■ cakephp-fixture-factories
https://github.com/vierge-noire/cakephp-fixture-factories#readme
■ テストの参考例
https://github.com/baserproject/ucmitz/blob/9bf5d6b1160b17da7ce0ea7ac08e794386da1e23/plugins/baser-core/tests/TestCase/Model/Validation/SiteValidationTest.php#L96

事前に、コマンドを利用してファクトリークラスの作成が必要となります。

2022-08-28 04:10 UTC, HungDV2022 commented on plugins/bc-search-index/tests/TestCase/Service/SearchIndexesAdminServiceTest.php
> +    protected $fixtures = [
@ryuring 
コメントの修正しました、
確認お願いします

2022-08-29 04:51 UTC, ryuring commented on plugins/bc-search-index/tests/TestCase/Service/SearchIndexesAdminServiceTest.php
> +        $rs = $this->SearchIndexesAdminService->getViewVarsForIndex($sites, $request);
@HungDV2022 引数が、$sites ではなく、$searchIndexes ですね。
SearchIndexFactory を作成してください。

2022-08-29 05:54 UTC, HungDV2022 commented on plugins/bc-search-index/tests/TestCase/Service/SearchIndexesAdminServiceTest.php
> +        $rs = $this->SearchIndexesAdminService->getViewVarsForIndex($sites, $request);
@ryuring 
コメントの修正しました、
確認お願いします

2022-08-29 06:57 UTC, ryuring commented on plugins/baser-core/tests/Factory/SearchIndexesFactory.php
> +    public function suspended()
@HungDV2022 このメソッド不要です

2022-08-29 07:05 UTC, ryuring requested changes
@HungDV2022 レビュー入れています。よろしくお願いします。

2022-08-29 07:05 UTC, ryuring commented on plugins/bc-search-index/tests/TestCase/Service/SearchIndexesAdminServiceTest.php
> +        $request = $this->getRequest('/')->withQueryParams(['user_group_id' => 1]);
@HungDV2022 SearchIndexesService::createAdminIndexConditions() には、user_group_id はないですね。無理やりパラメーターつけなくていいですよ。

2022-08-29 07:05 UTC, ryuring commented on plugins/bc-search-index/tests/TestCase/Service/SearchIndexesAdminServiceTest.php
> +        $this->assertEquals(count($expected), count($rs['sites']));
@HungDV2022 このテストは不要です。

2022-08-29 07:05 UTC, ryuring commented on plugins/bc-search-index/tests/TestCase/Service/SearchIndexesAdminServiceTest.php
> +        SiteFactory::make(10)->setField('status', 1)->persist();
@HungDV2022 データは１個あればよいかと思います。余計な負荷をかけたくないので。この↓の行も

2022-08-29 08:11 UTC, HungDV2022 commented
@ryuring 
コメントの修正しました、
確認お願いします

2022-08-29 08:37 UTC, ryuring commented on plugins/bc-search-index/tests/TestCase/Service/SearchIndexesAdminServiceTest.php
> +        SiteFactory::make(10)->setField('status', 1)->persist();
> この↓の行も

これできてないですね @HungDV2022

2022-08-29 09:14 UTC, HungDV2022 commented on plugins/bc-search-index/tests/TestCase/Service/SearchIndexesAdminServiceTest.php
> +        SiteFactory::make(10)->setField('status', 1)->persist();
@ryuring
コメントの修正しました、
確認お願いします

2022-08-29 10:02 UTC, ryuring commented
@HungDV2022 ありがとうございます。最後に１点。
こちらのドキュメントに書いているのですが、使ったテーブルの $fixtures を記述しないと、このテストクラスが終わった後の次のテストクラスでデータが初期化されずエラーになってしまう場合があります。
$fixtures の記述をお願いします。
https://baserproject.github.io/5/ucmitz/test/fixture#%E3%83%87%E3%83%BC%E3%82%BF%E3%81%AE%E5%88%9D%E6%9C%9F%E5%8C%96%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

2022-08-29 10:09 UTC, HungDV2022 commented
> @HungDV2022 ありがとうございます。最後に１点。 こちらのドキュメントに書いているのですが、使ったテーブルの $fixtures を記述しないと、このテストクラスが終わった後の次のテストクラスでデータが初期化されずエラーになってしまう場合があります。 $fixtures の記述をお願いします。 https://baserproject.github.io/5/ucmitz/test/fixture#%E3%83%87%E3%83%BC%E3%82%BF%E3%81%AE%E5%88%9D%E6%9C%9F%E5%8C%96%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

@ryuring 
こちらを追加しました
確認お願いします

2022-08-29 10:47 UTC, merged

2022-08-29 10:47 UTC, ryuring commented
@HungDV2022 長らくありがとうございました、マージしました！