fix #818 BaserCore\Plugin::bootstrap() のユニットテストを調整
baserproject/ucmitz pull request #832
Opened 2022-08-26 02:48 UTC by HungDV2022

2022-08-27 02:52 UTC, ryuring commented on plugins/baser-core/tests/TestCase/PluginTest.php
> +        $this->assertTrue(is_array($event->listeners('Controller.initialize')));
@HungDV2022 もともとテストが存在してなかったんですね。失礼しました。

グローバルイベントマネージャーのテストは、全てのイベントが呼び出されている事を確認しなくても大丈夫です。
```php
$this->assertTrue(is_array($event->listeners('Controller.startup')));
$this->assertTrue(is_array($event->listeners('Controller.beforeRender')));
```
↓
```php
$this->assertTrue(is_array($event->listeners('Controller.startup')));
```

そのかわりに、他の処理のテストができていないのでこちらを追加してください。
 - Configure::read('App.paths.plugins') にて、`baserproject` が追加されていること
 - CONFIG . 'setting.php' が存在する場合に読み込まれていること
 - DebugKit のオンオフ切り替え
 - Authenticationプラグインが読み込まれていること
 - Migrations プラグインが読み込まれていること
 - Configure::read('BcApp.defaultAdminTheme') が読み込まれていること
 - Configure::read('BcApp.defaultFrontTheme') が読み込まれていること
 - BcUtil::getEnablePlugins() で取得できるプラグインが読み込まれていること
 - Plugin::setupDefaultTemplatesPath() が呼び出されていること

お手数おかけしますがよろしくお願いします。

2022-08-29 03:30 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/PluginTest.php
> +        $this->assertTrue(is_array($event->listeners('Controller.initialize')));
@ryuring 
コメントの修正しました
確認お願いします

2022-08-29 04:53 UTC, ryuring commented
@HungDV2022 テストが失敗してしまっていますので確認お願いします。

2022-08-29 06:32 UTC, HungDV2022 commented
@ryuring 
こちらコメントの修正しました
確認お願いします

2022-08-29 06:52 UTC, ryuring requested changes
@HungDV2022 再レビューいれています。よろしくお願いします。

2022-08-29 06:52 UTC, ryuring commented on plugins/baser-core/tests/TestCase/PluginTest.php
> +use http\Env;
@HungDV2022 ここはアッパーキャメルケースですね

2022-08-29 06:52 UTC, ryuring commented on plugins/baser-core/tests/TestCase/PluginTest.php
> +            '/var/www/html/vendor/baserproject/',
同じものが２つはいっているのはおかしいですね。本体のコードが間違っているかもしれません。 @HungDV2022

2022-08-29 06:52 UTC, ryuring commented on plugins/baser-core/tests/TestCase/PluginTest.php
> +        $this->assertNotNull(\Cake\Core\Plugin::getCollection()->get('DebugKit'));
DebugKit が存在しないオフのテストを追加お願いします。 @HungDV2022

2022-08-29 06:52 UTC, ryuring commented on plugins/baser-core/tests/TestCase/PluginTest.php
> +        if (file_exists(CONFIG . 'setting.php')) {
実際に setting.php が存在するテストが書かれていません @HungDV2022

2022-08-29 08:29 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/PluginTest.php
> +            '/var/www/html/vendor/baserproject/',
@ryuring 
こちらは本体のコードを修正しなければなりませんか

2022-08-29 08:32 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/PluginTest.php
> +        $this->assertNotNull(\Cake\Core\Plugin::getCollection()->get('DebugKit'));
@ryuring 
`  if (!filter_var(env('USE_DEBUG_KIT', true), FILTER_VALIDATE_BOOLEAN)) `

ENVファイルに直接値を呼びるなのでDebugKit が存在しないオフテスト方法がわからないですから教えていただけませんか

2022-08-29 08:33 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/PluginTest.php
> +        if (file_exists(CONFIG . 'setting.php')) {
@ryuring   
` $this->assertTrue(Configure::isConfigured('setting'));`
こちらのように修正しますでしょうか

2022-08-29 08:45 UTC, ryuring commented on plugins/baser-core/tests/TestCase/PluginTest.php
> +        $this->assertNotNull(\Cake\Core\Plugin::getCollection()->get('DebugKit'));
一時的に .env を書き換えてうまくいきませんかね？ @HungDV2022 

このコードが参考になるかもしれません。
https://github.com/baserproject/ucmitz/blob/fdfa52eabbad1deed140a5149076708f58022666/plugins/baser-core/tests/TestCase/BcPluginTest.php#L279

2022-08-29 08:46 UTC, ryuring commented on plugins/baser-core/tests/TestCase/PluginTest.php
> +        if (file_exists(CONFIG . 'setting.php')) {
setting.php を一時的に作成して対応しましょう。
@HungDV2022

2022-08-29 08:49 UTC, ryuring commented on plugins/baser-core/tests/TestCase/PluginTest.php
> +            '/var/www/html/vendor/baserproject/',
@HungDV2022 おそらくですが、テスト実行の前段階で bootstrap は呼び出されているはずですので、テストの中でbootstrap を呼び出す前に確認したら大丈夫だと思います。

2022-08-29 10:10 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/PluginTest.php
> +use http\Env;
@ryuring
こちらコメントの修正しました
確認お願いします

2022-08-29 10:10 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/PluginTest.php
> +            '/var/www/html/vendor/baserproject/',
@ryuring
こちらコメントの修正しました
確認お願いします

2022-08-29 10:10 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/PluginTest.php
> +        $this->assertNotNull(\Cake\Core\Plugin::getCollection()->get('DebugKit'));
@ryuring
こちらコメントの修正しました
確認お願いします

2022-08-29 10:11 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/PluginTest.php
> +        if (file_exists(CONFIG . 'setting.php')) {
@ryuring
こちらコメントの修正しました
確認お願いします

2022-08-29 10:51 UTC, ryuring requested changes

2022-08-29 10:51 UTC, ryuring commented on plugins/baser-core/tests/TestCase/PluginTest.php
> +# Used as a default to seed config/.env which
@HungDV2022 .env は、こんなにいらないですね。コメントなどは消して必要なコードだけでお願いします。

2022-08-29 10:51 UTC, ryuring commented on plugins/baser-core/tests/TestCase/PluginTest.php
> +/**
@HungDV2022 setting.php は、こんなにいらないですね。コメントなどは消して必要なコードだけでお願いします。

2022-08-29 11:03 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/PluginTest.php
> +# Used as a default to seed config/.env which
@ryuring
こちらコメントの修正しました
確認お願いします

2022-08-29 11:03 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/PluginTest.php
> +/**
@ryuring
こちらコメントの修正しました
確認お願いします

2022-08-30 00:01 UTC, ryuring requested changes
@HungDV2022 レビューいれています。よろしくお願いします。

2022-08-30 00:01 UTC, ryuring commented on plugins/baser-core/tests/TestCase/PluginTest.php
> +        $file->write('export APP_NAME="ucmitz"
@HungDV2022 ファイルを変更する場合は、元に戻す処理が必要です。
そうしないと他のテストに影響を及ぼす可能性があるためです。

1. バックアップを作成する
2. ファイルを変更する
3. テストを実行する
4. バックアップより元に戻す。

2022-08-30 00:01 UTC, ryuring commented on plugins/baser-core/tests/TestCase/PluginTest.php
> +        $fileSetting = new File('config/'. 'setting.php');
@HungDV2022 新しくファイルを作成する場合は削除が必要です。ゴミファイルが残ってしまうためです。
1. ファイルを作成する
2. テストを実行する
3. ファイルを削除する

2022-08-30 00:25 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/PluginTest.php
> +        $file->write('export APP_NAME="ucmitz"
@ryuring 
こちらコメントの修正しました
確認お願いします

2022-08-30 00:25 UTC, HungDV2022 commented on plugins/baser-core/tests/TestCase/PluginTest.php
> +        $fileSetting = new File('config/'. 'setting.php');
@ryuring 
こちらコメントの修正しました
確認お願いします

2022-08-31 02:16 UTC, ryuring commented
@HungDV2022 諸々、ありがとうございます。マージしますね。

2022-08-31 02:16 UTC, merged