fix #840 SearchIndexesService::delete() のユニットテスト
baserproject/ucmitz pull request #859
Opened 2022-08-31 00:32 UTC by HungDV2022

2022-08-31 02:32 UTC, ryuring commented
@HungDV2022 こちらもコンフリクト解消をお願いしますー

2022-08-31 03:26 UTC, HungDV2022 commented
@ryuring 
コンフリクトを修正しました
確認お願いします

2022-08-31 03:49 UTC, ryuring requested changes

2022-08-31 03:49 UTC, ryuring commented on plugins/bc-search-index/tests/TestCase/Service/SearchIndexesServiceTest.php
> +        $searchIndexesService = new SearchIndexesService();
@HungDV2022 `$this->SearchIndexesService` が利用できます。

2022-08-31 03:49 UTC, ryuring commented on plugins/bc-search-index/tests/TestCase/Service/SearchIndexesServiceTest.php
> +        SearchIndexFactory::make(['title' => 'test data delete', 'type' => 'admin', 'site_id' => 1], 1)->persist();
@HungDV2022  `'id' => 1` を指定すれば、`getIndex()` でなく、`get()` が使えます。

2022-08-31 05:52 UTC, HungDV2022 commented on plugins/bc-search-index/tests/TestCase/Service/SearchIndexesServiceTest.php
> +        SearchIndexFactory::make(['title' => 'test data delete', 'type' => 'admin', 'site_id' => 1], 1)->persist();
@ryuring コメントの修正しました
確認お願いします

2022-08-31 05:52 UTC, HungDV2022 commented on plugins/bc-search-index/tests/TestCase/Service/SearchIndexesServiceTest.php
> +        $searchIndexesService = new SearchIndexesService();
@ryuring コメントの修正しました
確認お願いします

2022-09-01 02:38 UTC, ryuring commented
@HungDV2022 再度、コンフリクト解消お願いします。

2022-09-01 02:54 UTC, HungDV2022 commented
@ryuring 
 コンフリクトを修正しました。
確認お願いします

2022-09-01 06:56 UTC, merged